version: '3.7'  # Docker Compose 파일 형식 버전

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10  # 공식 이미지 사용
    #    build:
    #      context: ./elasticsearch
    container_name: es  # 생성될 컨테이너 이름
    environment:
      - discovery.type=single-node  # 단일 노드 모드 (클러스터 구성 아님)
      - bootstrap.memory_lock=true  # 메모리 잠금 설정 (성능 개선)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 자바 힙 메모리 설정 (512MB 고정)
    ulimits:
      memlock:
        soft: -1  # 메모리 잠금의 soft limit 해제
        hard: -1  # 메모리 잠금의 hard limit 해제
    ports:
      - "9200:9200"  # 로컬 포트 9200 → 컨테이너의 9200 포트로 연결 (REST API용)
    networks:
      - esnet  # 같은 네트워크에 Kibana 연결

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10  # 사용할 Kibana 이미지
    container_name: kibana  # 생성될 Kibana 컨테이너 이름
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200  # Elasticsearch 서버 주소 지정
    ports:
      - "5601:5601"  # 로컬 포트 5601 → 컨테이너의 5601 포트로 연결 (웹 UI)
    networks:
      - esnet  # Elasticsearch와 같은 네트워크로 설정

networks:
  esnet:
    driver: bridge  # 기본 브리지 네트워크 사용 (컨테이너끼리 통신 가능)